services:
  - type: web
    name: prof-warlock
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SAVE_INBOUND_EMAILS
        value: false
      - key: POSTMARK_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: WEBHOOK_SECRET_TOKEN
        sync: false
    healthCheckPath: /health 