openapi: 3.1.0
info:
  title: Prof. Warlock API
  description: API for generating natal charts and stats
  version: 1.0.0
paths:
  /natal-chart:
    post:
      summary: Generate a natal chart
      operationId: generateNatalChart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                birth_day:
                  type: integer
                birth_month:
                  type: integer
                birth_year:
                  type: integer
                birth_time:
                  type: string
                  format: time
                  pattern: '^\d{2}:\d{2}$'
                birth_place:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
              required:
                - first_name
                - last_name
                - birth_day
                - birth_month
                - birth_year
                - birth_time
      responses:
        '200':
          description: Natal chart generated successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "natal_chart.png"
                    id:
                      type: string
                      example: "natal_charts/20231108123456_abcdef12.png"
                    mime_type:
                      type: string
                      example: "image/png"
                    download_link:
                      type: string
                      example: "https://kodkafa.s3.eu-central-1.amazonaws.com/natal_charts/20231108123456_abcdef12.png"
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /natal-stats:
    post:
      summary: Get natal stats
      operationId: getNatalStats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                birth_day:
                  type: integer
                birth_month:
                  type: integer
                birth_year:
                  type: integer
                birth_time:
                  type: string
                  format: time
                  pattern: '^\d{2}:\d{2}$'
                birth_place:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
                today_day:
                  type: integer
                today_month:
                  type: integer
                today_year:
                  type: integer
                today_time:
                  type: string
                  format: time
                  pattern: '^\d{2}:\d{2}$'
              required:
                - first_name
                - last_name
                - birth_day
                - birth_month
                - birth_year
                - birth_time
      responses:
        '200':
          description: Natal stats retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  full_report:
                    type: string
                  sun_sign:
                    type: string
                  moon_sign:
                    type: string
                  rising_sign:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error 